### ISSUE TITLE
Consider using `markdown` for note source files?

### ISSUE THREAD

**Issue by langfield** [jamsinclair/open-anki-jlpt-decks#10]
**Disclaimer.** This is a shameless plug for my own tool.

Hey! Love what you folks are doing here! It's super cool to see Anki decks on GitHub with real contributions, PRs, and issues.

I was wondering if you'd be interested in converting your repository format over to use `markdown` for the notes? Here's what it might look like:

```markdown
## Note
nid: 1875
model: Open Anki JLPT Vocab
tags: JLPT, JLPT_1
markdown: false

### expression
ロマンチック

### reading
ロマンチック

### meaning
romantic
```

I've generated this using a [tool](https://github.com/langfield/ki) I've been building for the last half-year or so. It is built specifically for deck maintainers, to facilitate small diffs, large numbers of contributors, and easy builds. You can build your `.apkg` files in GitHub actions, or a CI pipeline of your choice, and then distribute them as GitHub releases. The repository format is optimized for human-readability:

```
    ├── 食い違う.md
    ├── 飲み込む.md
    ├── 飼育.md
    ├── 飽和.md
    ├── 養う.md
    ├── 養護.md
    ├── 首脳.md
    ├── 首輪.md
    ├── 首飾り.md
    ├── 香辛料.md
    ├── 馴々しい.md
    ├── 駄作.md
    ├── 駆けっこ.md
    ├── 駆け足.md
    ├── 騒動.md
    ├── 驚異.md
    ├── 骨董品.md
    ├── 高原.md
    ├── 高尚.md
    ├── 魂.md
    ├── 鮮やか.md
    ├── 鳥居.md
    ├── 麻.md
    ├── 麻痺.md
    ├── 麻酔.md
    ├── 黄金.md
    └── 黒字.md

3 directories, 2701 files
```

(If you know Kanji...)

If you're interested, I would love to help you get a workflow set up! Here's the [documentation](https://langfield.github.io/ki/).

**Comment by jamsinclair** [comment]
Apologies for belated reply @langfield. That looks like a really cool project and would be useful for many maintainers.

At this point shifting all cards to separate files seems like more of a maintenance burden for this particular project. Keeping all the words in one file allows for easy batch updates, quick content overview and seems more beneficial to me at this time.

I'll keep an eye out on your progress and wish you all the best. Nice to see innovation in this space 👏
