### ISSUE TITLE
Missing N2 vocab

### ISSUE THREAD

**Issue by jamesrm9235** [jamsinclair/open-anki-jlpt-decks#12]
Hello,

I found 158 missing N2 words. I discovered them when merging this repo's N2 deck with my own. I'm attaching a TSV file containing the words.

If accepted, I can add them to the `n2.csv` through a pull request.

[missing.txt](https://github.com/jamsinclair/open-anki-jlpt-decks/files/11746172/missing.txt)

**Comment by jamsinclair** [comment]
Thanks @jamesrm9235! The sources for this repo are years old so it's very likely there may be some missing or out-of-date words.

Do you have a source or link to where you got your deck or these words from? I just want to make sure we have reputable source so people can focus on what is necessary for the test.

**Comment by jamesrm9235** [comment]
No problem! I still found a lot of new words to add to my own deck.

I referred to jisho.org. The words are tagged "jlpt n2" according to the site. I'm attaching an updated file with links for each word.

[missing-with-ref-link.txt](https://github.com/jamsinclair/open-anki-jlpt-decks/files/11777192/missing-with-ref-link.txt)

**Comment by jamsinclair** [comment]
Thanks for confirming that @jamesrm9235.

I've added the new words in #14.

I also sorted the deck, to easily see the new words of yours that I added refer to the commit 7434abc9aed2778e70bfd00adebae6f8998790ca
