### ISSUE TITLE
Font in the guide column

### ISSUE THREAD

**Issue by vuxvix** [jamsinclair/open-anki-jlpt-decks#17]
Hi!
When I open csv files for editing. I notice that the content in the Guide column is special characters (HYeQ[!t+v+ ; emfZ/!E,?[....). I don't know if it's a font error or what. thanks for any help!

**Comment by jamsinclair** [comment]
Hey @vuxvix, feel free to ignore the column `guid`, those special characters are used by Anki to keep reference of notes.

It stands for Globally Unique Identifier (guid). It is used internally by Anki to identify notes. By storing this in the CSV we can safely update meanings, readings etc. and update decks without affecting your progress in Anki.

If you want to contribute new readings, don't worry about that field either. This project will autogenerate it.

**Comment by jamsinclair** [comment]
I should probably do a better job explaining the format so I've added a section to https://github.com/jamsinclair/open-anki-jlpt-decks/blob/main/CONTRIBUTING.md#csv-format

**Comment by vuxvix** [comment]
Hi jamsinclair,
Thanks for your quick response. I'm looking for a way to show the next columns in Back Templete. It's not very intuitive to me.

**Comment by jamsinclair** [comment]
>  show the next columns in Back Templete.

I think your message may have some typos. What do you want to display on the back template?

**Comment by vuxvix** [comment]
With some additional time spent learning Anki, I m now able to add content to the backs temp.
